# Generated by Django 4.1.5 on 2023-01-28 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumeapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resumeapp.languagelevel', verbose_name='Language level'),
        ),
        migrations.AddField(
            model_name='experience',
            name='professional_roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resumeapp.professionalrole', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumeapp.resume', verbose_name='Resume'),
        ),
    ]
