# Generated by Django 4.1.5 on 2023-01-28 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumeapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employment',
            options={'verbose_name': 'Вид занятости', 'verbose_name_plural': 'Виды занятости'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Предыдущее место работы', 'verbose_name_plural': 'Предыдущие места работы'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='languagelevel',
            options={'verbose_name': 'Уровень владения языком', 'verbose_name_plural': 'Уровни владения языком'},
        ),
        migrations.AlterModelOptions(
            name='professionalrole',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Ключевые навыки', 'verbose_name_plural': 'Ключевые навыки'},
        ),
        migrations.AlterField(
            model_name='employment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='employment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Вид занятости'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='experience',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='finished_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название предыдущего места работы'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='professional_roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resumeapp.professionalrole', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumeapp.resume', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='language',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resumeapp.languagelevel', verbose_name='Уровень владения'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Уровень владения'),
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='professionalrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='professionalrole',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='professionalrole',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='professionalrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='resume',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='employment',
            field=models.ManyToManyField(to='resumeapp.employment', verbose_name='Вид занятости'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='key_skills',
            field=models.ManyToManyField(to='resumeapp.skill', verbose_name='Клчюевые навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.ManyToManyField(to='resumeapp.language', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='professional_roles',
            field=models.ManyToManyField(to='resumeapp.professionalrole', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='schedule',
            field=models.ManyToManyField(to='resumeapp.schedule', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип графика'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='skill',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название навыка'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
