# Generated by Django 4.1.5 on 2023-01-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_alter_employment_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='professional_roles',
            field=models.CharField(max_length=150, verbose_name='Должность'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='professional_roles',
        ),
        migrations.DeleteModel(
            name='ProfessionalRole',
        ),
        migrations.AddField(
            model_name='resume',
            name='professional_roles',
            field=models.CharField(default=1, max_length=150, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
