# Generated by Django 4.1.5 on 2023-01-28 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='Short name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('vacancy_hh_id', models.PositiveIntegerField(verbose_name='ID vacancy')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('area_name', models.CharField(max_length=150, verbose_name='Location')),
                ('salary_from', models.PositiveIntegerField(default=0, verbose_name='Salary from')),
                ('salary_to', models.PositiveIntegerField(default=0, verbose_name='Salary to')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('candidate_experience_months', models.PositiveIntegerField(default=0, verbose_name="Candidate's experience (months)")),
                ('branded_description', models.TextField(blank=True, verbose_name='Description')),
                ('professional_roles', models.CharField(max_length=50, verbose_name='Professional roles')),
                ('response_url', models.CharField(blank=True, max_length=250, verbose_name='Response URL')),
                ('published_hh_at', models.DateTimeField(verbose_name='Published on hh at')),
                ('created_hh_at', models.DateTimeField(verbose_name='Created on hh at')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vacancies', to='vacancyapp.currency', verbose_name='Currency')),
                ('employment', models.ManyToManyField(to='resumeapp.employment', verbose_name='Employment')),
                ('key_skills', models.ManyToManyField(to='resumeapp.skill', verbose_name='Skills')),
                ('languages', models.ManyToManyField(to='resumeapp.language', verbose_name='Language')),
                ('schedule', models.ManyToManyField(to='resumeapp.schedule', verbose_name='Work schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
