# Generated by Django 4.1.5 on 2023-01-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_alter_employment_options_alter_experience_options_and_more'),
        ('vacancyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='currency',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='short_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='area_name',
            field=models.CharField(max_length=150, verbose_name='Месторасположение'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='branded_description',
            field=models.TextField(blank=True, verbose_name='Описание в форамте HTML'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidate_experience_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт работы кандидата(months)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана: '),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_hh_at',
            field=models.DateTimeField(verbose_name='Время создания вакансии (на hh.ru)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vacancies', to='vacancyapp.currency', verbose_name='Вид валюты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.ManyToManyField(to='resumeapp.employment', verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна ли вакансия на агрегаторе?'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='key_skills',
            field=models.ManyToManyField(to='resumeapp.skill', verbose_name='Требуемые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='languages',
            field=models.ManyToManyField(to='resumeapp.language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='professional_roles',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_hh_at',
            field=models.DateTimeField(verbose_name='Время публикации вакансии (на hh.ru)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='response_url',
            field=models.CharField(blank=True, max_length=250, verbose_name='URL отклика'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарплата от'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарплата до'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.ManyToManyField(to='resumeapp.schedule', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_hh_id',
            field=models.PositiveIntegerField(verbose_name='ID вакансии на HH'),
        ),
    ]
