# Generated by Django 4.1.5 on 2023-01-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday date'),
        ),
    ]
