# Generated by Django 4.1.5 on 2023-01-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_employment_languagelevel_position_schedule_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userapp.languagelevel', verbose_name='Language level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
