# Generated by Django 4.1.5 on 2023-01-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started')),
                ('finished_at', models.DateTimeField(auto_now=True, verbose_name='Finished')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userapp.position', verbose_name='Position')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='userapp.resume', verbose_name='Resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
