# Generated by Django 4.1.5 on 2023-01-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сurrency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='Short name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Position',
            new_name='ProfessionalRole',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='position',
            new_name='professional_roles',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='position',
            new_name='professional_roles',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill',
        ),
        migrations.AddField(
            model_name='resume',
            name='key_skills',
            field=models.ManyToManyField(to='userapp.skill', verbose_name='Skills'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('vacancy_hh_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID vacancy')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('area_name', models.CharField(max_length=150, verbose_name='Location')),
                ('salary_from', models.PositiveIntegerField(default=0, verbose_name='Salary from')),
                ('salary_to', models.PositiveIntegerField(default=0, verbose_name='Salary to')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('candidate_experience_months', models.PositiveIntegerField(default=0, verbose_name="Candidate's experience (months)")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('branded_description', models.TextField(blank=True, verbose_name='Description')),
                ('response_url', models.CharField(blank=True, max_length=250, verbose_name='Url')),
                ('professional_roles', models.CharField(max_length=50, verbose_name='')),
                ('published_hh_at', models.DateTimeField(verbose_name='Published on hh at')),
                ('created_hh_at', models.DateTimeField(verbose_name='Created on hh at')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vacancys', to='userapp.сurrency', verbose_name='Currency')),
                ('employment', models.ManyToManyField(to='userapp.employment', verbose_name='Employment')),
                ('key_skills', models.ManyToManyField(to='userapp.skill', verbose_name='Skills')),
                ('languages', models.ManyToManyField(to='userapp.language', verbose_name='Language')),
                ('schedule', models.ManyToManyField(to='userapp.schedule', verbose_name='Work schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
