# Generated by Django 4.1.5 on 2023-01-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_сurrency_rename_position_professionalrole_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.DeleteModel(
            name='Сurrency',
        ),
    ]
